version: "3"

services:
    broker-service:
        build:
            context: ./broker-service
            dockerfile: broker-service.dockerfile
        ports:
            - "8010:8010"
        deploy:
            mode: replicated
            replicas: 1
        restart: always